# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HappyNail' do

# Firebase SDK
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'

end
